apiVersion: v1
kind: PersistentVolume
metadata:
  name: ragh-mysql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: /mnt/data/ragh-mysql