apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  namespace: ffid
spec:
  selector:
    app: ffid-wordpress
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31001