apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptf-mysql
  namespace: ptf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ptf-mysql
  template:
    metadata:
      labels:
        app: ptf-mysql
    spec:
      containers:
      - name: ptf-mysql
        image: mysql:5.7
        envFrom:
        - configMapRef:
            name: mysql-config
        - secretRef:
            name: mysql-secret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: ptf-mysql-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: ptf-mysql-volume
        persistentVolumeClaim:
          claimName: ptf-mysql-pvc