apiVersion: apps/v1
kind: Deployment
metadata:
  name: pflg-wordpress
  namespace: pflg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pflg-wordpress
  template:
    metadata:
      name: pflg-wordpress
      labels:
        app: pflg-wordpress
    spec:
      containers:
      - name: pflg-wordpress
        image: wordpress:6.5-php8.3-apache
        envFrom:
        - configMapRef:
            name: wp-config
        - secretRef:
            name: wp-secret
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wp-persistent-storage
        persistentVolumeClaim:
          claimName: pflg-wp-pvc