apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: uiPkXUQmzpxN5PqPVG8I
  MYSQL_PASSWORD: uiPkXUQmzpxN5PqPVG8I
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
stringData:
  WORDPRESS_DB_PASSWORD: uiPkXUQmzpxN5PqPVG8I
